function EEG_roi = moveSource2DataField(EEG)
EEG_roi = EEG;
try
    EEG_roi.data = EEG.etc.src.act;
catch
    error('The src structure is missing, you need to call pop_inverseSolution first.');
end
EEG_roi.etc = rmfield(EEG_roi.etc,'src');
EEG_roi.nbchan = size(EEG_roi.data,1);
EEG_roi.chanlocs = struct('labels',[],'X',[],'Y',[],'Z',[],'ref',[],'theta',[],'radius',[],'sph_theta',[],'sph_phi',[],'sph_radius',[],'type', 'EEG','urchan',[]);
hm = headModel.loadFromFile(EEG.etc.src.hmfile);
xyz = hm.getCentroidROI(hm.atlas.label);
for r=1:EEG_roi.nbchan
    EEG_roi.chanlocs(r) = struct('labels',hm.atlas.label{r},...
        'X',xyz(r,1),...
        'Y',xyz(r,2),...
        'Z',xyz(r,3),...
        'ref','', ...
        'theta',[], ...
        'radius',[], ...
        'sph_theta', [], ...
        'sph_phi',[], ...
        'sph_radius',[], ...
        'type', 'EEG', ...
        'urchan', []);
end